# Juicebox Config

motd = "Welcome to Juicebox"

[security]
password = ""

[client]
discovery_period = 5

[server]
name = "Juicebox"
address = "0.0.0.0"
port = 8181
ffmpeg_path = ""

[storage]
downloads = "downloads"
database = "data.db"
archive = "cache.txt"